version: '3'

services:
  redis:
    container_name: redis-proxy
    image: redis:alpine
    hostname: redis_boot
    ports:
      - "6379:6379"
    command: redis-server --port 6379
    labels:
      - "name=redis"
      - "mode=standalone"